name: Publish Docker image and debian package

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  stage-debian:
    name: "Build debian package"
    runs-on: ubuntu-latest
    environment:
      name: staging

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y cmake curl iputils-ping libboost-filesystem-dev libboost-system-dev libboost-thread-dev
      
      - name: Build source code
        run: |
          mkdir build
          cd build
          cmake ..
          NO_ASAN=1 cmake -DCMAKE_BUILD_TYPE=Release -DINSTALL_FOLDER="${{ github.workspace }}/artof-core/usr/bin" .. && make -j4 install

      - name: Build debian package
        run: |
          dpkg-deb --build artof-core artof-core-dev.deb

      - uses: actions/upload-artifact@v4
        with:
          name: artof-core (dev)
          path: artof-core-dev.deb

