name: Publish Docker image and debian package

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  stage-docker:
    name: "Push artof-system to Docker Hub (tag: dev)"
    runs-on: ubuntu-latest
    environment:
      name: staging

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push version
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ vars.DOCKER_HUB_REGISTRY }}/${{ vars.DOCKER_IMAGE_NAME}}:dev

  stage-debian:
    name: "Build debian package"
    runs-on: ubuntu-latest
    environment:
      name: staging

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y cmake curl iputils-ping libboost-filesystem-dev libboost-system-dev libboost-thread-dev
      
      - name: Build source code
        run: |
          mkdir build
          cd build
          cmake ..
          NO_ASAN=1 cmake -DCMAKE_BUILD_TYPE=Release -DINSTALL_FOLDER="${{ github.workspace }}/artof-core/usr/bin" .. && make -j4 install

      - name: Build debian package
        run: |
          dpkg-deb --build artof-core artof-core-dev.deb

      - uses: actions/upload-artifact@v4
        with:
          name: artof-core (dev)
          path: artof-core-dev.deb

